---
version: "2.0"

# Juno Mainnet Example using public providers.

services:  
  rpc-cache:
    image: reecepbcups/rpc-cache:0.0.9
    env:
      # NOTE - most up to date will be in the docker-compose.yml file
      - REMOTE_CONFIG_TIME_FILE=https://raw.githubusercontent.com/Reecepbcups/cosmos-endpoint-cache/main/configs/cache_times.json      
      - RPC_PREFIX=junorpc_1
      - ENABLE_COUNTER=false
      - USE_BACKUP_AS_PRIMARY=false
      # Use your own node IPs here as http://
      - RPC_URL=https://rpc.juno.strange.love:443
      - BACKUP_RPC_URL=https://juno-rpc.polkachu.com
      - RPC_WEBSOCKET=ws://15.204.143.232:26657/websocket
      - NODE_MONIKER=reecepbcups
      - RPC_LISTEN_ADDRESS=HIDDEN
      - NODE_TM_VERSION=HIDDEN
      - COINGECKO_ENABLED=true
      # - COINGECKO_API_KEY=HERE
      - COINGECKO_CACHE_SECONDS=6 # do not change if you do not have an API key.
      - COINGECKO_IDS=cosmos,juno-network,osmosis,canto
      - COINGECKO_FIAT=usd,eur,gbp
      - RPC_TITLE=Juno Docker RPC
      - RPC_CUSTOM_TEXT=<a href="https://twitter.com/Reecepbcups_/status/1617396571188133888?s=20&t=OKi00IkStINFqYVweZXlaw">Custom caching solution active</a><br><a href="https://juno-api.reece.sh">My Juno REST API</a><br>
    expose:
      - port: 5001
        to:
          - global: true       
      - port: 80
        to:
          - global: true

  api-cache:
    image: reecepbcups/api-cache:0.0.9
    env:
      # NOTE - most up to date will be in the docker-compose.yml file
      - REMOTE_CONFIG_TIME_FILE=https://raw.githubusercontent.com/Reecepbcups/cosmos-endpoint-cache/main/configs/cache_times.json      
      - REST_PREFIX=junoapi
      - USE_BACKUP_AS_PRIMARY=false
      # Use your own node IPs here as http://
      - REST_URL=https://api.juno.strange.love:443
      - BACKUP_REST_URL=https://juno-api.polkachu.com
      - NODE_MONIKER=reecepbcups
      - ENABLE_COUNTER=false
      - API_TITLE=Juno Docker API
      - DISABLE_SWAGGER_UI=false
    expose:
      - port: 5000
        to:
          - global: true       

profiles:
  compute:
    redis:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    rpc-cache:
      resources:
        cpu:
          # Must use 2+ CPU (1 for websocket, one for processing requests)
          units: 2.0
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    api-cache:
      resources:
        cpu:
          units: 1.25
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
          - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"
      pricing:
        rpc-cache: 
          denom: uakt
          amount: 10000
        api-cache: 
          denom: uakt
          amount: 10000


deployment:
  rpc-cache:
    akash:
      profile: rpc-cache
      count: 1
  api-cache:
    akash:
      profile: api-cache
      count: 1