# docker build -f Dockerfile.rest -t juno_rest .
# docker run -d --rm --name juno_rest --network=host -p 5001:5001 juno_rest
FROM python:3.9

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 5001

CMD ["gunicorn", "--conf", "conf.py", "--bind", "0.0.0.0:5001", "rest.rest:app"]